backend:
  name: git-gateway
  branch: main

media_folder: "slike"

collections:
  - name: "novice"
    label: "Novice"
    folder: "_novice"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Naslov", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Kategorija", name: "kategorija", widget: "select", options: ["ÄŒlani", "Akademija", "Tabor", "Klub"] }
      - { label: "Kratki opis", name: "opis", widget: "text" }
      - { label: "Naslovna slika", name: "slika", widget: "image", required: false }
      - { label: "Vsebina", name: "body", widget: "markdown" }
